import { Role } from '../types';

export const seedTasks = [
  {
    name: 'Installation de chantier',
    owner_role: 'Project Manager' as Role,
    start_date: '2026-01-06',
    end_date: '2026-01-20',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Terrassement',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-01-15',
    end_date: '2026-02-25',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Fondations production',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-02-20',
    end_date: '2026-04-23',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Charpente métallique',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-04-08',
    end_date: '2026-06-21',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Couverture & bardage',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-05-20',
    end_date: '2026-08-05',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Dallage',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-06-06',
    end_date: '2026-07-21',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Fondations administration/social',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-05-06',
    end_date: '2026-07-06',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Élévation',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-06-21',
    end_date: '2026-09-05',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Plancher',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-07-21',
    end_date: '2026-09-19',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Équipements industriels',
    owner_role: 'Project Manager' as Role,
    start_date: '2026-08-07',
    end_date: '2026-10-21',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots architecturaux',
    owner_role: 'Architect' as Role,
    start_date: '2026-08-21',
    end_date: '2026-11-04',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots techniques - Électronique',
    owner_role: 'Chief of Electronics' as Role,
    start_date: '2026-09-06',
    end_date: '2026-11-20',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots techniques - Plomberie',
    owner_role: 'Chief of Plumbing' as Role,
    start_date: '2026-09-06',
    end_date: '2026-11-20',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Aménagement extérieur',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2026-10-07',
    end_date: '2026-11-25',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Réception EXT 01',
    owner_role: 'Project Manager' as Role,
    start_date: '2026-11-20',
    end_date: '2026-11-30',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Réception EXT 02',
    owner_role: 'Project Manager' as Role,
    start_date: '2026-11-25',
    end_date: '2026-12-05',
    percent_done: 0,
    status: 'On Track' as const,
  },
];
