import { Role } from '../types';

export const seedTasks = [
  {
    name: 'Installation de chantier',
    owner_role: 'Project Manager' as Role,
    start_date: '2024-11-01',
    end_date: '2024-11-15',
    percent_done: 100,
    status: 'Done' as const,
  },
  {
    name: 'Terrassement',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2024-11-10',
    end_date: '2024-12-20',
    percent_done: 90,
    status: 'On Track' as const,
  },
  {
    name: 'Fondations production',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2024-12-15',
    end_date: '2025-02-15',
    percent_done: 65,
    status: 'On Track' as const,
  },
  {
    name: 'Charpente métallique',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-02-01',
    end_date: '2025-04-15',
    percent_done: 30,
    status: 'On Track' as const,
  },
  {
    name: 'Couverture & bardage',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-03-15',
    end_date: '2025-05-30',
    percent_done: 15,
    status: 'Delayed' as const,
    delay_reason: 'Awaiting material delivery from supplier',
  },
  {
    name: 'Dallage',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-04-01',
    end_date: '2025-05-15',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Fondations administration/social',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-03-01',
    end_date: '2025-04-30',
    percent_done: 20,
    status: 'On Track' as const,
  },
  {
    name: 'Élévation',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-04-15',
    end_date: '2025-06-30',
    percent_done: 5,
    status: 'On Track' as const,
  },
  {
    name: 'Plancher',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-05-15',
    end_date: '2025-07-15',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Équipements industriels',
    owner_role: 'Project Manager' as Role,
    start_date: '2025-06-01',
    end_date: '2025-08-15',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots architecturaux',
    owner_role: 'Architect' as Role,
    start_date: '2025-06-15',
    end_date: '2025-08-30',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots techniques - Électronique',
    owner_role: 'Chief of Electronics' as Role,
    start_date: '2025-07-01',
    end_date: '2025-09-15',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Lots techniques - Plomberie',
    owner_role: 'Chief of Plumbing' as Role,
    start_date: '2025-07-01',
    end_date: '2025-09-15',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Aménagement extérieur',
    owner_role: 'Construction Contractor' as Role,
    start_date: '2025-08-01',
    end_date: '2025-09-20',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Réception EXT 01',
    owner_role: 'Project Manager' as Role,
    start_date: '2025-09-15',
    end_date: '2025-09-25',
    percent_done: 0,
    status: 'On Track' as const,
  },
  {
    name: 'Réception EXT 02',
    owner_role: 'Project Manager' as Role,
    start_date: '2025-09-20',
    end_date: '2025-09-30',
    percent_done: 0,
    status: 'On Track' as const,
  },
];
